#!/bin/bash

echo "========================================="
echo "PDFShuffle Screenshot Capture Helper"
echo "========================================="
echo ""
echo "Instructions:"
echo "1. The app should be open now"
echo "2. Take screenshots using macOS screenshot tool:"
echo "   - Press Cmd+Shift+4"
echo "   - Then press SPACE to capture the window"
echo "   - Click on the PDFShuffle window"
echo ""
echo "Take screenshots of:"
echo "  - Main view (Split tab)"
echo "  - Merge tab"
echo "  - Extract tab"
echo "  - Reorder tab"
echo ""
echo "Screenshots will be saved to your Desktop by default"
echo ""
echo "After taking screenshots, run this to convert them:"
echo "  ./process-screenshots.sh"
echo ""
read -p "Press Enter when you've taken all screenshots..."

echo ""
echo "Now, move your screenshots from Desktop to appstore-screenshots/"
echo "Name them: screenshot-1.png, screenshot-2.png, etc."
